name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read  # to fetch code
  actions: write  # to cancel previous workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: "Pre-commit check - `pre-commit run -a`"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  test-model:
    needs: [pre-commit]
    name: "(${{ matrix.model }} - model random init and forward"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: ["deepseek_r1_jax", "kimi_k2", "llama3", "llama4", "qwen3", "gpt_oss"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: astral-sh/setup-uv@7edac99f961f18b581bbd960d59d049f04c0002f # v6.4.1
        with:
          enable-cache: true
      - run: |
          uv venv --seed --python 3.12 venv
          source venv/bin/activate
          pip install -U uv pip
          cd ${{ matrix.model }}
          which uv
          which python3
          which python
          uv pip install -e . pytest
          python3 -m pytest tests/test_model.py
